import { ReactNode } from "react";

import type { Metadata } from "next";

import { Roboto } from "next/font/google";

import "@/styles/main/main.scss";

import { Footer } from "../components/modules/Footer/Footer";
import { Main } from "../components/modules/Main/Main";

import { Wrapper } from "../components/containers/Wrapper/Wrapper";
import { ThemeProvider } from "@/components/ui/ThemeContext/ThemeContext";

const robotoFont = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Графік відключення електроенергії у Львівській області",
  description: "Generated by create next app",
  icons: "/icons/energy_logo.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="uk">
      <body className={robotoFont.className}>
        <ThemeProvider>
          <Wrapper>
            <Main>{children}</Main>
            <Footer />
          </Wrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
